package com.edaoe.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSite<M extends BaseSite<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setHost(String host) {
		set("host", host);
		return (M)this;
	}
	
	public String getHost() {
		return getStr("host");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}

	public M setDesc(String desc) {
		set("desc", desc);
		return (M)this;
	}
	
	public String getDesc() {
		return getStr("desc");
	}

	public M setUserId(Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public Long getUserId() {
		return getLong("userId");
	}

	public M setTheme(String theme) {
		set("theme", theme);
		return (M)this;
	}
	
	public String getTheme() {
		return getStr("theme");
	}

	public M setVersion(String version) {
		set("version", version);
		return (M)this;
	}
	
	public String getVersion() {
		return getStr("version");
	}

	public M setIsValid(Boolean isValid) {
		set("isValid", isValid);
		return (M)this;
	}
	
	public Boolean getIsValid() {
		return get("isValid");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setLastUseTime(java.util.Date lastUseTime) {
		set("lastUseTime", lastUseTime);
		return (M)this;
	}
	
	public java.util.Date getLastUseTime() {
		return get("lastUseTime");
	}

}
