package com.edaoe.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public M setNickname(String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public String getNickname() {
		return getStr("nickname");
	}

	public M setAvatar(String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public String getAvatar() {
		return getStr("avatar");
	}

	public M setRole(String role) {
		set("role", role);
		return (M)this;
	}
	
	public String getRole() {
		return getStr("role");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}
	
	public String getPassword() {
		return getStr("password");
	}

	public M setSalt(String salt) {
		set("salt", salt);
		return (M)this;
	}
	
	public String getSalt() {
		return getStr("salt");
	}

	public M setIsValid(Boolean isValid) {
		set("isValid", isValid);
		return (M)this;
	}
	
	public Boolean getIsValid() {
		return get("isValid");
	}

	public M setLastSiteId(Long lastSiteId) {
		set("lastSiteId", lastSiteId);
		return (M)this;
	}
	
	public Long getLastSiteId() {
		return getLong("lastSiteId");
	}

	public M setSiteLimit(Integer siteLimit) {
		set("siteLimit", siteLimit);
		return (M)this;
	}
	
	public Integer getSiteLimit() {
		return getInt("siteLimit");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
