package com.edaoe.model;

import com.edaoe.model.base.BaseSite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Site extends BaseSite<Site> {
	public static final Site dao = new Site().dao();
	
}
